CREATE SEQUENCE "IRRIGATION_SEQUENCE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PLOT_CONFIG_SEQUENCE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PLOT_SEQUENCE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PREDICTION_SEQUENCE" START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE "PLOT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PLOT_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PLOT_SEQUENCE",
    "CREATION_DATE" TIMESTAMP,
    "MODIFICATION_DATE" TIMESTAMP,
    "AREA" DOUBLE,
    "CROP" VARCHAR(255),
    "LOCATION" VARCHAR(255),
    "NAME" VARCHAR(255) NOT NULL
);
ALTER TABLE "PLOT" ADD CONSTRAINT "CONSTRAINT_2" PRIMARY KEY("ID");

CREATE TABLE "PLOT_CONFIG"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PLOT_CONFIG_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PLOT_CONFIG_SEQUENCE",
    "CREATION_DATE" TIMESTAMP,
    "MODIFICATION_DATE" TIMESTAMP,
    "AMOUNT_OF_WATER" DOUBLE,
    "START_TIME" TIMESTAMP,
    "END_TIME" TIMESTAMP,
    "INTERVAL_UNIT" VARCHAR(255),
    "TIME_INTERVAL" INTEGER,
    "PLOT_ID" BIGINT NOT NULL
);
ALTER TABLE "PLOT_CONFIG" ADD CONSTRAINT "CONSTRAINT_7" PRIMARY KEY("ID");
ALTER TABLE "PLOT_CONFIG" ADD CONSTRAINT "FKTCEOS811H7VIX3RNFO28PEB5L" FOREIGN KEY("PLOT_ID") REFERENCES "PLOT"("ID") NOCHECK;

CREATE TABLE "IRRIGATION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "IRRIGATION_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "IRRIGATION_SEQUENCE",
    "CREATION_DATE" TIMESTAMP,
    "MODIFICATION_DATE" TIMESTAMP,
    "STATUS" VARCHAR(255) NOT NULL,
    "PLOT_ID" BIGINT NOT NULL
);
ALTER TABLE "IRRIGATION" ADD CONSTRAINT "CONSTRAINT_F" PRIMARY KEY("ID");
ALTER TABLE "IRRIGATION" ADD CONSTRAINT "FKTJL7IP8DLPUD4K7HGA9L0MTR1" FOREIGN KEY("PLOT_ID") REFERENCES "PLOT"("ID") NOCHECK;

CREATE TABLE "PREDICTION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PREDICTION_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PREDICTION_SEQUENCE",
    "CROP" VARCHAR(255),
    "AREA" DOUBLE,
    "AMOUNT_OF_WATER" DOUBLE,
    "START_TIME" TIMESTAMP,
    "END_TIME" TIMESTAMP,
    "INTERVAL_UNIT" VARCHAR(255),
    "TIME_INTERVAL" INTEGER
);
ALTER TABLE "PREDICTION" ADD CONSTRAINT "CONSTRAINT_8" PRIMARY KEY("ID");
